version: '3.9'

services:
  csms:
    hostname: csms_201
    ports:
      - "8888:8887"

  k6:
    image: grafana/k6:latest
    # Run the performance tests
    user: ${UID}:${GID}
    depends_on:
      - csms
    networks:
      - sim
    command: run /scripts/rapid-connect-disconnect.ts --vus 10 --duration 30s --out json=ocpp_201.json --summary-export=summary_201.json
    volumes:
      - ./k6:/scripts
      - ./results:/home/k6
    environment:
      # To prevent clashing in CI
      - WS_PORT=8888
      - WS_HOST=csms_201

networks:
  sim:
    driver: bridge
