name: Test
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE

  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE

  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Run tests
        run: |
          docker compose -f docker-compose.test.yaml up unit_test --abort-on-container-exit
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: unit_coverage_${{ github.sha }}
          path: ./coverage.out

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Download coverage from unit tests
        uses: actions/download-artifact@v4
        with:
          name: unit_coverage_${{ github.sha }}
      - name: Run integration tests
        run: |
          docker compose -f docker-compose.test.yaml up integration_test --abort-on-container-exit
      - name: Merge coverage
        run: |
          sed '1d;$d' integration_coverage.out >> coverage.out
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ github.sha }}
          path: ./coverage.out

  performance:
    name: Performance tests
    runs-on: ubuntu-latest
    needs: unit
    permissions:
      pull-requests: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run OCPP 1.6 performance tests
        id: ocpp16-perf-test
        run: |
          make perf-tests-ocpp16-ci
          echo "SUMMARY_16=$(jq -r './results' summary_16.json)" >> "$GITHUB_OUTPUT"

      - name: Run OCPP 2.0.1 performance tests
        id: ocpp201-perf-test
        run: |
          make perf-tests-ocpp201-ci
          echo "SUMMARY_201=$(jq -r './results' summary_201.json)" >> "$GITHUB_OUTPUT"

      - name: Report performance test results
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: performance_test_results_${{ github.sha }}
          retention-days: 14

      - name: Post summary to PR
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v3
        if: github.event_name == 'pull_request'
        with:
          message: |
            ## Performance Test Results
            ${{steps.ocpp16-perf-test.outputs.SUMMARY_16}}
            ${{steps.ocpp201-perf-test.outputs.SUMMARY_201}}
          pr-number: ${{ github.event.pull_request.number }}
          comment-tag: execution

  publish_coverage:
    runs-on: ubuntu-latest
    # Unit and integration tests must be run before publishing coverage
    needs: [ unit, integration ]
    name: Publish coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Download coverage from tests
        uses: actions/download-artifact@v4
        with:
          name: coverage_${{ github.sha }}
      - name: Publish
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}